services:
  postgres:
    image: postgres:15-alpine
    container_name: sweatlog_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${HOST_PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sweatlog_network

volumes:
  postgres_data:

networks:
  sweatlog_network:
    driver: bridge
